services:
  # Weaviate vector database
  weaviate:
    image: semitechnologies/weaviate:1.19.6
    ports:
      - "8081:8080"  # Changed from 8080:8080 to avoid port conflict
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Elasticsearch for BM25 search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G

  # Application container
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5000"  # Changed to 5005:5000 to avoid port conflicts
    volumes:
      - ./data:/app/data
      - ./app:/app/app
      - ./src:/app/src
    depends_on:
      - weaviate
      - elasticsearch
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - VOYAGE_API_KEY=${VOYAGE_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - WEAVIATE_URL=http://weaviate:8080
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - HOST=0.0.0.0
      - PORT=5000
    networks:
      - app-network
    command: python -m app.chat_server

networks:
  app-network:
    driver: bridge

volumes:
  weaviate_data:
  es_data: